# Generated by Django 5.1 on 2024-08-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcollection',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskcollection',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
